### ISSUE TITLE
Bug - open-ai module has changed which makes breaking changes in LLM

### ISSUE THREAD

**Issue by TomBurdge** [TracecatHQ/functime#129]
Once installed the modules for the LLM addon with `pip install functime[llm]` the connection to OpenAI doesn't work with the current `openai_call` function.

This is because OpenAI have changed how you call the API for chat completion (see the how to in their [ReadMe](https://github.com/openai/openai-python)).

I have made a [pull request](https://github.com/TracecatHQ/functime/pull/128) which fixes this. 
Happy to change anything once reviewed!

**Comment by topher-lo** [comment]
Closed by #128
