### ISSUE TITLE
1i freq error with auto_lightgbm

### ISSUE THREAD

**Issue by pcgm-team** [TracecatHQ/functime#130]
My polars frame looks like this in the first two columns:
```
symbol    timestamp
str    u32
"TIE"    1
"FDX"    1
```

The other columns are float type.
but when I run it through `auto_lightgbm(freq= '1i')`; I get the error:

```
--> 124     return fit_cv(
    125         y=y,
    126         X=X,
    127         forecaster_cls=partial(self.forecaster, **self.kwargs),
    128         freq=self.freq,
    129         min_lags=self.min_lags,
    130         max_lags=self.max_lags,
    131         max_horizons=self.max_horizons,
    132         strategy=self.strategy,

--> 176     if X.columns[0] == y.columns[0]:
    177         X = self._enforce_string_cache(X.lazy().collect())
    178     X = X.lazy()

AttributeError: 'list' object has no attribute 'columns'
```
Data size was around 7 million rows and 50 columns if that is relevant.

**Comment by topher-lo** [comment]
Just replicated. Will fix this regression today and release the fix on Monday. Thanks for the report 👍

**Comment by topher-lo** [comment]
I'll need more information. Do you have a minimal reproducible example? What `y` and `X` did you pass into `.fit`?

**Comment by topher-lo** [comment]
Fixed by https://github.com/TracecatHQ/functime/commit/88c4d6341fd2e5d42b74ef494ce061a2a5e74d95
